{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shtanko",
    "module": "logging-starter",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 9845,
          "sha512": "1e039747a46ba0a01a146d5e97462d6b9522c84275306b338bb01b7dc017b1ce1ad6403f2d2de41c651e9843dd05f61c9eb52cba18d3d03881d98c0561026d0a",
          "sha256": "2b20f229914d8fd3fd52376947bc206b49ab6e23647c203f1177f691cda9b86e",
          "sha1": "d21907e8f0d80145f4aa35025b07d1316429dfc9",
          "md5": "c4eef0bd1d50ff65bfb5abd37fc82772"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.1-SNAPSHOT.jar",
          "url": "logging-starter-1.1-SNAPSHOT.jar",
          "size": 9845,
          "sha512": "1e039747a46ba0a01a146d5e97462d6b9522c84275306b338bb01b7dc017b1ce1ad6403f2d2de41c651e9843dd05f61c9eb52cba18d3d03881d98c0561026d0a",
          "sha256": "2b20f229914d8fd3fd52376947bc206b49ab6e23647c203f1177f691cda9b86e",
          "sha1": "d21907e8f0d80145f4aa35025b07d1316429dfc9",
          "md5": "c4eef0bd1d50ff65bfb5abd37fc82772"
        }
      ]
    }
  ]
}
