{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.shtanko",
    "module": "logging-starter",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 12683,
          "sha512": "24e47b7d87a311d2d021b0c52f9059101655d65fff079bf91d1a8f9c9f2745b890d4cfb29eb5d614ae6bf5ea9397a64bc7e37aae2b261db9420553aab2f94db7",
          "sha256": "8cef0c058c717c324a7be39f7d39f5927b1643e2e075d9b63027b8e04bb6e7f4",
          "sha1": "512033c6beb0acd6c32a93c71f7991132df4af3f",
          "md5": "77721be4d216cd4a0f6287078d0ffcab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-1.3-SNAPSHOT.jar",
          "url": "logging-starter-1.3-SNAPSHOT.jar",
          "size": 12683,
          "sha512": "24e47b7d87a311d2d021b0c52f9059101655d65fff079bf91d1a8f9c9f2745b890d4cfb29eb5d614ae6bf5ea9397a64bc7e37aae2b261db9420553aab2f94db7",
          "sha256": "8cef0c058c717c324a7be39f7d39f5927b1643e2e075d9b63027b8e04bb6e7f4",
          "sha1": "512033c6beb0acd6c32a93c71f7991132df4af3f",
          "md5": "77721be4d216cd4a0f6287078d0ffcab"
        }
      ]
    }
  ]
}
